# Generated by Django 4.2.5 on 2023-09-28 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cosmonauts_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cosmonaut',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='cosmonaut',
            name='text',
        ),
    ]
